### ISSUE TITLE
关于本仓库目录结构的建议

### ISSUE THREAD

**Issue by ice-forever** [VinsonLaro/stable-diffusion-webui-chinese#1]
当前1018版本的仓库的目录结构与原版位于同一目录下，建议考虑让本仓库的根目录变为[localizations](https://github.com/VinsonLaro/stable-diffusion-webui-chinese/tree/main/localizations)目录而不是原版stable-diffusion-webui目录下。这样就可以实现原版的仓库可以正常拉取到stable-diffusion-webui并且本汉化文件的仓库拉取到stable-diffusion-webui的子目录localizations中。我认为这种方式可以方便两个仓库的文件的及时更新并且免去了麻烦的合并操作。
最后，感谢大佬的汉化！

**Comment by linfen0** [comment]
支持
