### ISSUE TITLE
请问一下哪里有原版的英文语言包文件啊？

### ISSUE THREAD

**Issue by Sostay** [VinsonLaro/stable-diffusion-webui-chinese#3]
菜鸡求教~

**Comment by VinsonLaro** [comment]
把语言切换到none，然后导出本地化模板，得到的json文件就是英文语音包(包括你装的插件)

**Comment by Sostay** [comment]
> 把语言切换到none，然后导出本地化模板，得到的json文件就是英文语音包(包括你装的插件)

我下载的整合包，选无 导出的也是中文。。能帮忙导一个给我吗？感恩……

**Comment by Sostay** [comment]
> > 把语言切换到none，然后导出本地化模板，得到的json文件就是英文语音包(包括你装的插件)
> 
> 我下载的整合包，选无 导出的也是中文。。能帮忙导一个给我吗？感恩……

更新了一下webui，已经有了~
