### ISSUE TITLE
启用本扩展后会导致openpose editor生成的骨架无法传输到txt2img

### ISSUE THREAD

**Issue by aiimagestudio** [VinsonLaro/stable-diffusion-webui-chinese#5]
启用该扩展后，openpose editor生成的骨架数据，在send to txt2img时无法正常传递，关闭本中文扩展后恢复正常，可能是汉化的bug。

**Comment by VinsonLaro** [comment]
openpose editor在传照片的时候会验证一遍“ControlNet”，然后再传过去，现在改好汉化没问题了现在
