### ISSUE TITLE
版本更新后无法正常加载中文页面，设置和之前一样，没什么问题。

### ISSUE THREAD

**Issue by billowssun** [VinsonLaro/stable-diffusion-webui-chinese#8]
版本更新后无法正常加载中文页面，设置和之前一样，没什么问题。

**Comment by saintzealot** [comment]
相同问题，使用了url和手工的方式都没有装上。url的方式，也并没有把对应的json文件下载到本地

**Comment by VinsonLaro** [comment]
啊，可以试试将webui退回到8ca50f8版本，最新版的webui本地化好像出bug了，等越南人修复吧

**Comment by billowssun** [comment]
了解

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: VinsonLaro ***@***.***>
发送时间: Saturday, May 13, 2023 10:20:00 PM
收件人: VinsonLaro/stable-diffusion-webui-chinese ***@***.***>
抄送: billows ***@***.***>; Author ***@***.***>
主题: Re: [VinsonLaro/stable-diffusion-webui-chinese] 版本更新后无法正常加载中文页面，设置和之前一样，没什么问题。 (Issue #8)


啊，可以试试将webui退回到8ca50f8版本，最新版的webui本地化好像出bug了，等越南人修复吧

―
